inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4 # Oldest version of Ruby we support
  NewCops: disable

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Lint/AssignmentInCondition:
  Enabled: false

# Enforcing this results in a lot of unnecessary indentation.
Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'lib/scss_lint/config.rb'
    - 'lib/scss_lint/cli.rb'

Style/OptionalBooleanParameter:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    reduce: inject

Style/Documentation:
  Exclude:
    - 'spec/scss_lint/**/*'
    - 'spec/scss_lint/linter/**/*'

Security/Eval:
  Exclude:
    - 'lib/scss_lint/sass/script.rb'

Style/FormatString:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'bin/scss-lint'
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'

Style/GuardClause:
  Enabled: true

Lint/SuppressedException:
  Exclude:
    - 'spec/scss_lint/cli_spec.rb'

Style/IfUnlessModifier:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/ExtraSpacing:
  Exclude:
    - '*.gemspec'

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/LineLength:
  Max: 103

# Reports false positives for `'.one #{$interpolated-string} .two .three {}'` (RuboCop v0.50.0)
Lint/InterpolationCheck:
  Enabled: false

Lint/Void:
  Exclude:
    - 'spec/**/*_spec.rb'

Naming/MethodParameterName:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/PerceivedComplexity:
  Max: 8

# Prefer curly braces except for %i/%w/%W, since those return arrays.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '()'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

# Renaming `has_something?` to `something?` obfuscates whether it is a "is-a" or
# a "has-a" relationship.
Naming/PredicateName:
  Enabled: false

# Forcing a particular name (e.g. |a, e|) for inject methods prevents you from
# choosing intention-revealing names.
Style/SingleLineBlockParams:
  Enabled: false

# YAML.safe_load isn't available on Ruby 2.0.0, which we still support
Security/YAMLLoad:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false
