name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  ci:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['2.4', '2.5', '2.6', '3.0', '3.1', '3.2.0', jruby]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
